spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jjdbc:mysql://mysql:3306/vrms_users?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET:default_dev_secret}
    expirationSeconds: 3600
